query getSeller($id: ID!) {
  seller(id: $id) @context(provider: "vtex.sellers-graphql") {
    name
    logo
    isActive
    description
    email
    exchangeReturnPolicy
    deliveryPolicy
    securityPrivacyPolicy
  }
}
